jenkins:
  systemMessage: "Addi-Aire Jenkins Server"
  mode: NORMAL
  numExecutors: 2
  labelString: "built-in"
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: true
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    unsecured:  # Allow anonymous access
  remotingSecurity:
    enabled: true
  slaveAgentPort: 50000
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: true
    usageStatisticsEnabled: true
    staticTokens:
      - name: "prometheus-metrics"
        id: "prometheus"
        value: "prometheus-token-123"  # You can change this token value
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  sSHD:
    port: -1

unclassified:
  location:
    url: "http://192.168.3.26:8080"
  globalLibraries:
    libraries:
      - name: "shared-library"
        defaultVersion: "main"
        implicit: true
        allowVersionOverride: true
        includeInChangesets: true
  prometheusConfiguration:
    collectDiskUsage: false
    collectingMetricsPeriodInSeconds: 120
    defaultNamespace: "jenkins"
    jobAttributeName: "jenkins_job"
    path: "/prometheus"
    useAuthenticatedEndpoint: false
    appendStatusToMetricName: false
    appendTypeToMetricName: false
  timestamperConfig:
    allPipelines: true
    systemTimeFormat: "HH:mm:ss"
    elapsedTimeFormat: "HH:mm:ss.S"

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
  maven:
    installations:
      - name: "Maven 3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"

jobs:
  - script: >
      folder('Infrastructure') {
          description('Infrastructure related jobs')
      }
      folder('Applications') {
          description('Application related jobs')
      }

credentials:
  system:
    domainCredentials:
      - domain:
          name: "global"
          description: "Global credentials"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: "jenkins"
              password: "change-me"
              description: "GitHub credentials" 