global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.3.26:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.3.26:9100']

  - job_name: 'jenkins'
    metrics_path: /jenkins/prometheus
    static_configs:
      - targets: ['192.168.3.26:8080']

  - job_name: 'elasticsearch'
    metrics_path: /_monitoring/metrics
    static_configs:
      - targets: ['192.168.3.26:9200']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.3.26:3001']

  - job_name: 'nginx'
    metrics_path: /health
    static_configs:
      - targets: ['192.168.3.26']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['192.168.3.26:9093']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.3.26:8082']
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [container_label_com_docker_compose_project]
        target_label: project 