apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.3.26:9090
    uid: prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    basicAuth: true
    basicAuthUser: elastic
    uid: elasticsearch
    secureJsonData:
      basicAuthPassword: addi-aire-elastic
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.12.1
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      interval: auto
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.3.26:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: $${__value.raw}

  - name: Tempo
    type: tempo
    access: proxy
    url: http://192.168.3.26:3200
    uid: tempo
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags: ["job", "instance", "pod", "namespace"]
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus 